### ISSUE TITLE
Missing tag

### ISSUE THREAD

**Issue by ploeghvander** [wwkimball/wwkimball-postfix#1]
Hello, this is an interesting module because all the others postfix modules seem to miss good Hiera support.
Problem now is that I want fix the version/tag so my r10k instance will always keep at the same version for this module.

Could you kindly add a tag to it?

Thanks a lot
Hendrik

**Comment by wwkimball** [comment]
Thank you very much for your interest in this module!  I'm so sorry for the delay in my response; GitHub failed to alert me to your request (no notifications, at all).

I haven't yet tagged this module because I haven't yet released it to the Puppet Forge.  I am trying to work out a couple of kinks in that process (my Puppet Strings documentation only sometimes appears out of Travis CI, sometimes Travis CI creates very different locations for the Puppet Strings documentation, and I don't yet have any acceptance testing).

I will tag the release as soon as I am able to publish to the Forge.

**Comment by wwkimball** [comment]
I have finally jumped through all of Travis CI and Puppet Forge's hoops to get the two to work together.  I have finally successfully published this module to the Puppet Forge with version 0.1.1.  This issue is now closed.

Thank you again for your interest.
